# -*- coding: utf-8 -*-
"""modul_penjumbelahan

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GM5hB_wsZbrYeGTsOnFblvqfSHR6dWPZ
"""

# Tulis code Anda disini
# Variable n
n = 10

# Looping angka n
for angka in range(1, n+1):
    print(angka)